[nr-k8s-otel-collector] feat: Add cpu and memory node utilization derived metrics (#1993)
#### Is this a new chart
NO IT IS NOT!!!

#### What this PR does / why we need it:
What's up ya'll it's your fave devs here, we're here again with this hot
new fresh PR.
Ya'll already know what this one is, it's been talked about for so long,
gained so much popularity even before it hit github.
We're here today to 
one: Fetch node allocatable metrics directly from the node Via Kubectl
and
TWO: Use those values to derive node utilization for memory and CPU. 


#### Which issue this PR fixes
N/A

#### Special notes for your reviewer:
Check it out, this query totally matches the kubectl top values. 
<img width="718" height="122" alt="image"
src="https://github.com/user-attachments/assets/202ce217-68ca-47e5-a6fc-921244947379"
/>

kubectl top yo
```
NAME                                        CPU(cores)   CPU(%)   MEMORY(bytes)   MEMORY(%)   
ip-10-0-22-90.us-west-1.compute.internal    419m         21%      3341Mi          47%         
ip-10-0-34-133.us-west-1.compute.internal   4m           0%       406Mi           5%          
ip-10-0-34-22.us-west-1.compute.internal    2m           0%       435Mi           5%          
ip-10-0-37-66.us-west-1.compute.internal    315m         16%      2944Mi          42%         
ip-10-0-63-169.us-west-1.compute.internal   282m         14%      3542Mi          50%         
ip-10-0-72-96.us-west-1.compute.internal    490m         25%      3373Mi          47% 
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove
unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

# Release Notes to Publish (nr-k8s-otel-collector)
If this PR contains changes in `nr-k8s-otel-collector`, please complete
the following section. All other charts should ignore this section.

<!--BEGIN-RELEASE-NOTES-->
## 🚀 What's Changed
* Added `node.cpu.usage.percentage` and `node.memory.usage.percentage`
derived metrics.
<!--END-RELEASE-NOTES-->

---------

Co-authored-by: Daniel Budziwojski <dbudziwojski@newrelic.com>

diff --git a/charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset.yaml b/charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset.yaml
--- a/charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset.yaml
+++ b/charts/nr-k8s-otel-collector/examples/k8s/rendered/daemonset.yaml
@@ -10,7 +10,7 @@ app.kubernetes.io/instance: nr-k8s-otel-collector
 app.kubernetes.io/managed-by: Helm
 app.kubernetes.io/name: nr-k8s-otel-collector
 app.kubernetes.io/version: 1.2.0
-helm.sh/chart: nr-k8s-otel-collector-0.9.3
+helm.sh/chart: nr-k8s-otel-collector-0.9.4
 spec:
   selector:
 matchLabels:
@@ -24,9 +24,56 @@ app.kubernetes.io/instance: nr-k8s-otel-collector
 app.kubernetes.io/name: nr-k8s-otel-collector
 component: daemonset
   annotations:
-checksum/config: f8cc3cc65da7e0454444f43187b064a282e76bc63917a3b629f5205b14f9597a
+checksum/config: a927fe84bb5aa454ae7797be3c40e6e39c4ba38b7541393a66ea1d001a443e80
 spec:
   serviceAccountName: nr-k8s-otel-collector
+  initContainers:
+- name: get-cpu-allocatable
+  image: bitnami/kubectl:latest
+  command:
+- sh
+- -c
+- |
+  NODE_NAME=$(echo $KUBE_NODE_NAME)
+  echo "Node Name: $KUBE_NODE_NAME"
+
+  export NODE_CPU_ALLOCATABLE=$(kubectl get node $NODE_NAME -o jsonpath='{.status.allocatable.cpu}')
+
+  if [[ -z "NODE_CPU_ALLOCATABLE" ]] || [[ "NODE_CPU_ALLOCATABLE" == "0" ]]; then
+echo "Could not retrieve CPU allocatable for node $NODE_NAME"
+exit 1
+  fi
+
+  # Convert milliCPU values to plain CPU values
+  if [[ $NODE_CPU_ALLOCATABLE == *m ]]; then
+# Strip the 'm' and convert the milliCPUs to CPUs
+export NODE_CPU_ALLOCATABLE=$(awk "BEGIN {print ${NODE_CPU_ALLOCATABLE%?} / 1000}")
+  fi
+
+  export NODE_MEMORY_ALLOCATABLE=$(kubectl get node $NODE_NAME -o jsonpath='{.status.allocatable.memory}' | numfmt --from=auto)
+
+  if [[ -z "NODE_MEMORY_ALLOCATABLE" ]] || [[ "NODE_MEMORY_ALLOCATABLE" == "0" ]]; then
+echo "Could not retrieve Memory allocatable for node $NODE_NAME"
+exit 1
+  fi
+
+  echo "NODE_CPU_ALLOCATABLE : $NODE_CPU_ALLOCATABLE"
+  echo "NODE_MEMORY_ALLOCATABLE : $NODE_MEMORY_ALLOCATABLE"
+  cp /temp-config/daemonset-config.yaml /final-config
+  yq -i '(.processors.metricsgeneration/calculate_percentage.rules[] | select(.name == "node.cpu.usage.percentage").scale_by) = env(NODE_CPU_ALLOCATABLE)' /final-config/daemonset-config.yaml
+  yq -i '(.processors.metricsgeneration/calculate_percentage.rules[] | select(.name == "node.memory.usage.percentage").scale_by) = env(NODE_MEMORY_ALLOCATABLE)' /final-config/daemonset-config.yaml
+  cat /final-config/daemonset-config.yaml
+  env:
+- name: KUBE_NODE_NAME
+  valueFrom:
+fieldRef:
+  apiVersion: v1
+  fieldPath: spec.nodeName
+  volumeMounts:
+- name: daemonset-config
+  mountPath: /temp-config
+- name: final-daemonset-config
+  mountPath: /final-config
   containers:
 - name: otel-collector-daemonset
   securityContext:
@@ -79,7 +126,7 @@ secretKeyRef:
 - name: varlogpods
   mountPath: /var/log/pods
   readOnly: true
-- name: daemonset-config
+- name: final-daemonset-config
   mountPath: /config
   volumes:
 - name: host-fs
@@ -88,6 +135,8 @@ path: /
 - name: varlogpods
   hostPath:
 path: /var/log/pods
+- name: final-daemonset-config
+  emptyDir: {}
 - name: daemonset-config
   configMap:
 name: nr-k8s-otel-collector-daemonset-config
diff --git a/charts/nr-k8s-otel-collector/templates/daemonset.yaml b/charts/nr-k8s-otel-collector/templates/daemonset.yaml
--- a/charts/nr-k8s-otel-collector/templates/daemonset.yaml
+++ b/charts/nr-k8s-otel-collector/templates/daemonset.yaml
@@ -34,6 +34,53 @@ spec:
   dnsConfig:
 {{- . | nindent 8 }}
   {{- end }}
+  initContainers:
+- name: get-cpu-allocatable
+  image: bitnami/kubectl:latest
+  command:
+- sh
+- -c
+- |
+  NODE_NAME=$(echo $KUBE_NODE_NAME)
+  echo "Node Name: $KUBE_NODE_NAME"
+
+  export NODE_CPU_ALLOCATABLE=$(kubectl get node $NODE_NAME -o jsonpath='{.status.allocatable.cpu}')
+
+  if [[ -z "NODE_CPU_ALLOCATABLE" ]] || [[ "NODE_CPU_ALLOCATABLE" == "0" ]]; then
+echo "Could not retrieve CPU allocatable for node $NODE_NAME"
+exit 1
+  fi
+
+  # Convert milliCPU values to plain CPU values
+  if [[ $NODE_CPU_ALLOCATABLE == *m ]]; then
+# Strip the 'm' and convert the milliCPUs to CPUs
+export NODE_CPU_ALLOCATABLE=$(awk "BEGIN {print ${NODE_CPU_ALLOCATABLE%?} / 1000}")
+  fi
+
+  export NODE_MEMORY_ALLOCATABLE=$(kubectl get node $NODE_NAME -o jsonpath='{.status.allocatable.memory}' | numfmt --from=auto)
+
+  if [[ -z "NODE_MEMORY_ALLOCATABLE" ]] || [[ "NODE_MEMORY_ALLOCATABLE" == "0" ]]; then
+echo "Could not retrieve Memory allocatable for node $NODE_NAME"
+exit 1
+  fi
+
+  echo "NODE_CPU_ALLOCATABLE : $NODE_CPU_ALLOCATABLE"
+  echo "NODE_MEMORY_ALLOCATABLE : $NODE_MEMORY_ALLOCATABLE"
+  cp /temp-config/daemonset-config.yaml /final-config
+  yq -i '(.processors.metricsgeneration/calculate_percentage.rules[] | select(.name == "node.cpu.usage.percentage").scale_by) = env(NODE_CPU_ALLOCATABLE)' /final-config/daemonset-config.yaml
+  yq -i '(.processors.metricsgeneration/calculate_percentage.rules[] | select(.name == "node.memory.usage.percentage").scale_by) = env(NODE_MEMORY_ALLOCATABLE)' /final-config/daemonset-config.yaml
+  cat /final-config/daemonset-config.yaml
+  env:
+- name: KUBE_NODE_NAME
+  valueFrom:
+fieldRef:
+  apiVersion: v1
+  fieldPath: spec.nodeName
+  volumeMounts:
+- name: daemonset-config
+  mountPath: /temp-config
+- name: final-daemonset-config
+  mountPath: /final-config
   containers:
 - name: otel-collector-daemonset
   {{- with include "nrKubernetesOtel.daemonset.securityContext.container" . }}
@@ -99,7 +146,7 @@ secretKeyRef:
 - name: varlogpods
   mountPath: /var/log/pods
   readOnly: true
-- name: daemonset-config
+- name: final-daemonset-config
   mountPath: /config
 {{- with .Values.daemonset.extraVolumeMounts }}
 {{- toYaml . | nindent 12 }}
@@ -113,6 +160,8 @@ path: /
 - name: varlogpods
   hostPath:
 path: /var/log/pods
+- name: final-daemonset-config
+  emptyDir: {}
 - name: daemonset-config
   configMap:
 name: {{ include "nrKubernetesOtel.daemonset.configMap.fullname" . }}
