[nr-ebpf-agent] Update OTLP port to 443 and init container fixes (#1929)
<!--
Thank you for contributing to New Relic's Helm charts. Before you submit
this PR we'd like to
make sure you are aware of our technical requirements:

*
https://github.com/newrelic-experimental/helm-charts/blob/master/CONTRIBUTING.md#technical-requirements

For a quick overview across what we will look at reviewing your PR,
please read
our review guidelines:

*
https://github.com/newrelic-experimental/helm-charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the
review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not
squash the
history. This will make it easier to identify new changes. The PR will
be squashed
anyways when it is merged. Thanks.

For fast feedback, please @-mention maintainers that are listed in the
Chart.yaml file.

Please make sure you test your changes before you push them. Once
pushed, a Github Action
will run across your changes and do some initial checks and linting.
These checks run
very quickly. Please check the results. We would like these checks to
pass before we
even continue reviewing your changes.
-->
#### Is this a new chart
No

#### What this PR does / why we need it:
- Update init-container base image to use `nr-ebpf-agent` image
- Set default latest image tags (for agent, client and Otel) in the helm
chart instead of picking it from the values.yaml. The image tags will be
kept empty by default.
- Update OTLP port to 443
- Proceed to agent deployment even on `init` container failure

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)`
format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove
unrelated fields.]
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[mychartname]`)

# Release Notes to Publish (nr-k8s-otel-collector)
If this PR contains changes in `nr-k8s-otel-collector`, please complete
the following section. All other charts should ignore this section.

<!--BEGIN-RELEASE-NOTES-->
## 🚀 What's Changed
* Tell the world about the latest changes in the chart.
<!--END-RELEASE-NOTES-->

---------

Co-authored-by: Sumit Suthar <ssuthar@newrelic.com>
Co-authored-by: kishan-k2io <kishan@k2io.com>

diff --git a/charts/nr-ebpf-agent/templates/nr-ebpf-agent-daemonset.yaml b/charts/nr-ebpf-agent/templates/nr-ebpf-agent-daemonset.yaml
--- a/charts/nr-ebpf-agent/templates/nr-ebpf-agent-daemonset.yaml
+++ b/charts/nr-ebpf-agent/templates/nr-ebpf-agent-daemonset.yaml
@@ -40,26 +40,27 @@ spec:
   {{- end }}
   initContainers:
   - name: kernel-header-installer
-image: amazonlinux:2
+image: docker.io/newrelic/newrelic-ebpf-agent:agent-0.2.9
 command:
   - "/bin/bash"
   - "-c"
   - |
 # Detect OS and install kernel headers accordingly
-# sleep 10000s
-if [ -f /host/etc/os-release ]; then \
-  . /host/etc/os-release; \
-  if [[ $ID == 'amzn' || $ID == 'centos' || $ID == 'rhel' ]]; then \
-echo 'Detected EKS/Amazon Linux or CentOS/RHEL. Installing kernel-devel...' && chroot /host /bin/bash -c "yum install -y kernel-devel-$(uname -r)"; \
-  elif [[ $ID == 'debian' || $ID == 'ubuntu' ]]; then \
-echo 'Detected Debian/Ubuntu. Installing linux-headers...' && chroot /host /bin/bash -c "apt-get update || true && apt-get install -y linux-headers-$(uname -r)"; \
-  # elif [[ $ID == 'cos' ]]; then \
-  #   echo 'Detected GKE/Container-Optimized OS. Installing linux-headers via toolbox...' && /host/usr/bin/toolbox apt-get update && /host/usr/bin/toolbox apt-get install -y linux-headers-$(uname -r)-amd; \
-  else \
-echo 'Unsupported OS: '$ID; exit 1; \
-  fi; \
-else \
-  echo '/host/etc/os-release not found'; exit 1; \
+if [ -f /host/etc/os-release ]; then
+  . /host/etc/os-release
+  if [[ $ID == 'amzn' || $ID == 'centos' || $ID == 'rhel' ]]; then
+echo 'Detected EKS/Amazon Linux or CentOS/RHEL. Installing kernel-devel...'
+chroot /host /bin/bash -c "yum install -y kernel-devel-$(uname -r)" || echo 'kernel-devel install failed, proceeding.'
+  elif [[ $ID == 'debian' || $ID == 'ubuntu' ]]; then
+echo 'Detected Debian/Ubuntu. Installing linux-headers...'
+chroot /host /bin/bash -c "apt-get update || true && apt-get install -y linux-headers-$(uname -r)" || echo 'linux-headers install failed, proceeding.'
+  else
+echo "Unsupported OS: $ID"
+echo "Proceeding without kernel header install."
+  fi
+else
+  echo "/host/etc/os-release not found"
+  echo "Proceeding without kernel header install."
 fi
 securityContext:
   privileged: true
@@ -69,7 +70,11 @@ volumeMounts:
 
   containers:
   - name: nr-ebpf-agent
-image: {{ .Values.ebpfAgent.image.repository }}:{{ .Values.ebpfAgent.image.tag }}
+image: {{- if .Values.ebpfAgent.image.tag }}
+  {{ .Values.ebpfAgent.image.repository }}:{{ .Values.ebpfAgent.image.tag }}
+{{- else }}
+  docker.io/newrelic/newrelic-ebpf-agent:agent-0.2.9
+{{- end }}
 imagePullPolicy: {{ .Values.ebpfAgent.image.pullPolicy }}
 resources: {{ .Values.ebpfAgent.resources | toYaml | nindent 10 }}
 env:
@@ -79,7 +84,7 @@ value: "/host"
 value: "{{ .Values.stirlingSources | default "socket_tracer,tcp_stats" }}"
   {{- include "generateTracingEnvVars" . | indent 10 }}
   - name: KUBERNETES_CLUSTER_DOMAIN
-value: "cluster.local" 
+value: "cluster.local"
   - name: NEW_RELIC_LOG_LEVEL
 value: "{{ .Values.logLevel }}"
   - name: NEW_RELIC_LOG_FILE_PATH
@@ -126,7 +131,11 @@ readOnly: true
   {{- end }}
   {{- end }}
   - name: nr-ebpf-client
-image: {{ .Values.ebpfClient.image.repository }}:{{ .Values.ebpfClient.image.tag }}
+image: {{- if .Values.ebpfClient.image.tag }}
+  {{ .Values.ebpfClient.image.repository }}:{{ .Values.ebpfClient.image.tag }}
+{{- else }}
+  docker.io/newrelic/newrelic-ebpf-agent:client-0.2.9
+{{- end }}
 imagePullPolicy: {{ .Values.ebpfClient.image.pullPolicy }}
 resources: {{ .Values.ebpfClient.resources | toYaml | nindent 10 }}
 env:
