Initial changes for init container

diff --git a/charts/nr-ebpf-agent/templates/nr-ebpf-agent-daemonset.yaml b/charts/nr-ebpf-agent/templates/nr-ebpf-agent-daemonset.yaml
--- a/charts/nr-ebpf-agent/templates/nr-ebpf-agent-daemonset.yaml
+++ b/charts/nr-ebpf-agent/templates/nr-ebpf-agent-daemonset.yaml
@@ -38,6 +38,36 @@ spec:
       dnsConfig:
         {{- . | nindent 8 }}
       {{- end }}
+      initContainers:
+      - name: kernel-header-installer
+        image: amazonlinux:2
+        command:
+          - "/bin/bash"
+          - "-c"
+          - |
+            # Detect OS and install kernel headers accordingly
+            sleep 1000s
+            chroot /host /bin/bash -c "\
+              if [ -f /etc/os-release ]; then \
+                . /etc/os-release; \
+                if [[ \$ID == 'amzn' || \$ID == 'centos' || \$ID == 'rhel' ]]; then \
+                  yum install -y kernel-devel-\$(uname -r); \
+                elif [[ \$ID == 'debian' || \$ID == 'ubuntu' ]]; then \
+                  apt-get update || apt-get install -y linux-headers-\$(uname -r); \
+                elif [[ \$ID == 'cos' ]]; then \
+                  toolbox run -- sudo apt-get install -y linux-headers-\$(uname -r); \
+                else \
+                  echo 'Unsupported OS: '\$ID; exit 1; \
+                fi; \
+              else \
+                echo '/etc/os-release not found'; exit 1; \
+              fi"    
+        securityContext:
+          privileged: true
+        volumeMounts:
+        - name: host-root-volume
+          mountPath: /host
+
       containers:
       - name: nr-ebpf-agent
         image: {{ .Values.ebpfAgent.image.repository }}:{{ .Values.ebpfAgent.image.tag }}
