[super-agent] L2 identity creation (#1546)
#### Is this a new chart
No
#### What this PR does / why we need it:
This PR adds L2 identity creation from L1 ClientID and ClientSecret. 
It maintains backwards compatibility so `userKey` can still be used, but
if ClientID and ClientSecret are present, the latter will be used.

As with `userKey`, a custom secret can be used to pass the ClientID and
ClientSecret.

#### Which issue this PR fixes
  - fixes https://new-relic.atlassian.net/browse/NR-343393

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove
unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

diff --git a/charts/super-agent/charts/super-agent-deployment/templates/preinstall-job-register-system-identity.yaml b/charts/super-agent/charts/super-agent-deployment/templates/preinstall-job-register-system-identity.yaml
--- a/charts/super-agent/charts/super-agent-deployment/templates/preinstall-job-register-system-identity.yaml
+++ b/charts/super-agent/charts/super-agent-deployment/templates/preinstall-job-register-system-identity.yaml
@@ -1,10 +1,17 @@
 {{- if include "newrelic-super-agent.auth.secret.shouldRunJob" . -}}
 {{- /*
-User key secret is used only in the step that create the system identity.
+SystemIdentity currently supports userKey and L1/L2 identities. (userKey to be deprecated)
+Both user key secret or L1/L2 identities are used only in the step that create the system identity.
 The secret that is created by the common-library does not allow to add annotations so the secret is removed
 once the installation hook is finished, so I have to add it as a hook.
+
+As both ways co-exist, we'll add a check to ensure at least one exits
 */ -}}
-{{- if not (include "newrelic.common.userKey._customSecretName" .) }}
+{{- if and (not (include "newrelic.common.userKey._customSecretName" .)) (not (include "newrelic.common.userKey._userKey" .)) (not (include "newrelic-super-agent.auth.customl1IdentitySecretName" .)) (not (include "newrelic-super-agent.auth.l1Identity" .)) -}}
+  {{- fail "You must specify a userKey/customUserKeySecretName or l1Identity/customl1IdentitySecretName" -}}
+{{- end -}}
+
+{{- if and (not (include "newrelic.common.userKey._customSecretName" .)) (include "newrelic.common.userKey._userKey" .) }}
 ---
 apiVersion: v1
 kind: Secret
@@ -18,14 +25,26 @@ helm.sh/hook-weight: "-1010"
   name: {{ include "newrelic.common.naming.truncateToDNSWithSuffix" (dict "name" (include "newrelic.common.naming.fullname" .) "suffix" "preinstall-user-key" ) }}
   namespace: {{ .Release.Namespace }}
 data:
-  {{- /*
-This secret is needed duplicating the userKey because it is in a helm hook and has a hook lifetime.
-Internal helpers to get the userKey do not fail in case it is empty so I need to test here if it is empty.
-   */}}
-  {{- if not (include "newrelic.common.userKey._userKey" .) }}
-{{- fail "You must specify a userKey or a customUserKeySecretName containing it" -}}
-  {{- end }}
   {{ include "newrelic.common.userKey.secretKeyName" . }}: {{ include "newrelic.common.userKey._userKey" . | b64enc }}
+{{- end }}
+
+{{/* L1/L2 Client Credentials */}}
+{{- if and (not (include "newrelic-super-agent.auth.customl1IdentitySecretName" .)) (include "newrelic-super-agent.auth.l1Identity" .) }}
+---
+apiVersion: v1
+kind: Secret
+metadata:
+  annotations:
+helm.sh/hook: pre-install,pre-upgrade
+helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
+helm.sh/hook-weight: "-1010"
+  labels:
+{{- include "newrelic.common.labels" . | nindent 4 }}
+  name: {{ include "newrelic-super-agent.auth.generatedIdentityCredentialsSecretName" . }}
+  namespace: {{ .Release.Namespace }}
+data:
+  {{ include "newrelic-super-agent.auth.l1IdentityCredentialsKey.clientIdKeyName" . }}: {{ include "newrelic-super-agent.auth.l1IdentityClientId" . | b64enc }}
+  {{ include "newrelic-super-agent.auth.l1IdentityCredentialsKey.clientSecretKeyName" . }}: {{ include "newrelic-super-agent.auth.l1IdentityClientSecret" . | b64enc }}
 {{- end }}
 ---
 apiVersion: batch/v1
@@ -45,17 +64,31 @@ spec:
   serviceAccountName: {{ include "newrelic.common.naming.truncateToDNSWithSuffix" (dict "name" (include "newrelic.common.serviceAccount.name" .) "suffix" "auth" ) }}
   containers:
 - name: register-system-identity
-  image: alpine 
+  image: alpine
   env:
+{{- if or  (include "newrelic.common.userKey._customSecretName" .) (include "newrelic.common.userKey._userKey" .) }}
 - name: USER_KEY
   valueFrom:
 secretKeyRef:
   {{- if include "newrelic.common.userKey._customSecretName" . }}
   name: {{ include "newrelic.common.userKey.secretName" . }}
   {{- else }}
-  name: {{ include "newrelic.common.naming.truncateToDNSWithSuffix" (dict "name" (include "newrelic.common.naming.fullname" .) "suffix" "preinstall-user-key" ) }}
+  name: {{ include "newrelic.common.userKey.generatedSecretName" . }}
   {{- end }}
   key: {{ include "newrelic.common.userKey.secretKeyName" . }}
+{{- end }}
+{{- if or (include "newrelic-super-agent.auth.customl1IdentitySecretName" .) (include "newrelic-super-agent.auth.l1Identity" .) }}
+- name: NEW_RELIC_AUTH_CLIENT_ID
+  valueFrom:
+secretKeyRef:
+  name: {{ include "newrelic-super-agent.auth.identityCredentialsSecretName" . }}
+  key: {{ include "newrelic-super-agent.auth.l1IdentityCredentialsKey.clientIdKeyName" . }}
+- name: NEW_RELIC_AUTH_CLIENT_SECRET
+  valueFrom:
+secretKeyRef:
+  name: {{ include "newrelic-super-agent.auth.identityCredentialsSecretName" . }}
+  key: {{ include "newrelic-super-agent.auth.l1IdentityCredentialsKey.clientSecretKeyName" . }}
+{{- end }}
   command:
 - ash
   args:
@@ -79,45 +112,130 @@ exit 0
   openssl rsa -in "$TEMPORAL_FOLDER/key" -pubout -out "$TEMPORAL_FOLDER/pub"
 
   echo Key generated, creating the identity...
-  for RETRY in 1 2 3; do
-HTTP_CODE=$(echo '{ "query":
-"mutation {
-  systemIdentityCreate(
-name: \"System Identity for Kubernetes cluster '{{ include "newrelic.common.cluster" . }}'\",
-organizationId: \"{{ include "newrelic-super-agent.auth.organizationId" . }}\",
-publicKey: \"'$(openssl enc -base64 -A -in "$TEMPORAL_FOLDER/pub")'\"
-  ) {
-clientId,
-name
-  }
-}"
-  }' | tr -d $'\n' | \
-  curl \
--w "%{http_code}" \
+  if [ "${NEW_RELIC_AUTH_CLIENT_ID:-}" != "" ] && [ "${NEW_RELIC_AUTH_CLIENT_SECRET:-}" != "" ]; then
+echo Starting with L1/L2 System Identity...
+############################################################
+# Get the L1 Access Token
+############################################################
+RESPONSE_FILE=$TEMPORAL_FOLDER/response_token.json
+for RETRY in 1 2 3; do
+  HTTP_CODE=$(echo '{"client_id": "'$NEW_RELIC_AUTH_CLIENT_ID'", "client_secret": "'$NEW_RELIC_AUTH_CLIENT_SECRET'", "grant_type": "client_credentials"}' | tr -d $'\n' | curl \
+-s -w "%{http_code}" \
 -H "Content-Type: application/json" \
--H "API-Key: $USER_KEY" \
--o "$TEMPORAL_FOLDER/response.json" \
---data @- \
-"{{ include "newrelic-super-agent.config.endpoints.systemIdentityRegistration" . }}"
-)
-if [ $HTTP_CODE -eq 200 ]; then
-  break
-fi
-echo "Error creating the new system identity. The API endpoint returned $HTTP_CODE. Retrying ($RETRY/3)..."
-sleep 2
-  done
-  if [ $HTTP_CODE -ne 200 ]; then echo HTTP_CODE=$HTTP_CODE ;exit 1; fi
+-o "$RESPONSE_FILE" \
+--data-binary @- \
+"{{ include "newrelic-super-agent.config.endpoints.tokenRenewal" . }}"
+  )
 
-  ERROR_MESSAGE=$(jq -r '.errors[0].message // "NOERROR"' "$TEMPORAL_FOLDER/response.json")
-  if [ "$ERROR_MESSAGE" != "NOERROR" ]; then
-echo "Failed to create a New Relic System Identity for OpAMP communication authentication. Please verify that your User Key is valid and that your Account Organization has the necessary permissions to create a System Identity: $ERROR_MESSAGE"
-exit 1
+  if [ $HTTP_CODE -eq 200 ]; then
+break
   fi
 
+  ERROR_MESSAGE=$(jq '.error_description // "invalid_request"' < "$TEMPORAL_FOLDER/response_token.json" | tr -d '"')
+
+  echo "Error getting system identity auth token. The API endpoint returned $HTTP_CODE: $ERROR_MESSAGE. Retrying ($RETRY/3)..."
+  sleep 2
+done
+
+if [ $HTTP_CODE -ne 200 ]; then
+  echo "Error getting system identity auth token"
+  exit 99
+fi
+
+ACCESS_TOKEN=$(jq  '.access_token' < "$RESPONSE_FILE" | tr -d '"' )
+
+############################################################
+# Create System Identity (L1/L2 System Identities)
+############################################################
+DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
+NAME="System Identity for $(hostname) - $DATE"
+
+for RETRY in 1 2 3; do
+  HTTP_CODE=$(echo '{ "query":
+  "mutation {
+create(
+  name: \"'$NAME'\",
+  organizationId: \"{{ include "newrelic-super-agent.auth.organizationId" . }}\",
+  publicKey: \"'$(openssl enc -base64 -A -in "$TEMPORAL_FOLDER/pub")'\"
+) {
+  clientId,
+  name
+}
+  }"
+}' | tr -d $'\n' | curl \
+  -s -w "%{http_code}" \
+  -H "Content-Type: application/json" \
+  -H "Authorization: Bearer $ACCESS_TOKEN" \
+  -o "$TEMPORAL_FOLDER/response.json" \
+  --data-binary @- \
+  "{{ include "newrelic-super-agent.config.endpoints.systemIdentityCreation" . }}"
+  )
+
+  if [ $HTTP_CODE -eq 200 ]; then
+break
+  fi
+
+  echo "Error creating L2 system identity. The API endpoint returned $HTTP_CODE. Retrying ($RETRY/3)..."
+  sleep 2
+done
+
+if [ $HTTP_CODE -ne 200 ]; then
+  exit 99
+fi
+
+ERROR_MESSAGE=$(jq '.errors[0].message // "NOERROR"' < "$TEMPORAL_FOLDER/response.json" | tr -d '"')
+if [ "$ERROR_MESSAGE" != "NOERROR" ]; then
+  echo "Failed to create a New Relic System Identity for Fleet Control communication authentication. Please verify that your User Key is valid and that your Account Organization has the necessary permissions to create a System Identity: $ERROR_MESSAGE"
+  exit 100
+fi
+
+CLIENT_ID=$(jq  '.data.create.clientId' < "$TEMPORAL_FOLDER/response.json" | tr -d '"' )
+  else
+echo Starting with Legacy UserApiKey System Identity...
+############################################################
+# Create System Identity (Legacy)
+############################################################
+for RETRY in 1 2 3; do
+  HTTP_CODE=$(echo '{ "query":
+  "mutation {
+systemIdentityCreate(
+  name: \"System Identity for Kubernetes cluster '{{ include "newrelic.common.cluster" . }}'\",
+  organizationId: \"{{ include "newrelic-super-agent.auth.organizationId" . }}\",
+  publicKey: \"'$(openssl enc -base64 -A -in "$TEMPORAL_FOLDER/pub")'\"
+) {
+  clientId,
+  name
+}
+  }"
+}' | tr -d $'\n' | \
+curl \
+  -w "%{http_code}" \
+  -H "Content-Type: application/json" \
+  -H "API-Key: $USER_KEY" \
+  -o "$TEMPORAL_FOLDER/response.json" \
+  --data @- \
+  "{{ include "newrelic-super-agent.config.endpoints.systemIdentityRegistration" . }}"
+  )
+  if [ $HTTP_CODE -eq 200 ]; then
+break
+  fi
+  echo "Error creating the new system identity. The API endpoint returned $HTTP_CODE. Retrying ($RETRY/3)..."
+  sleep 2
+done
+if [ $HTTP_CODE -ne 200 ]; then echo HTTP_CODE=$HTTP_CODE ;exit 1; fi
+
+ERROR_MESSAGE=$(jq -r '.errors[0].message // "NOERROR"' "$TEMPORAL_FOLDER/response.json")
+if [ "$ERROR_MESSAGE" != "NOERROR" ]; then
+  echo "Failed to create a New Relic System Identity for OpAMP communication authentication. Please verify that your User Key is valid and that your Account Organization has the necessary permissions to create a System Identity: $ERROR_MESSAGE"
+  exit 1
+fi
+
+CLIENT_ID=$(jq -r '.data.systemIdentityCreate.clientId' "$TEMPORAL_FOLDER/response.json")
+  fi
   echo Creating the secret '{{ include "newrelic-super-agent.auth.secret.name" . }}'...
   kubectl create secret generic --dry-run=client -o json \
 {{ include "newrelic-super-agent.auth.secret.name" . }} \
---from-literal=CLIENT_ID=$(jq -r '.data.systemIdentityCreate.clientId' "$TEMPORAL_FOLDER/response.json") \
+--from-literal=CLIENT_ID=$CLIENT_ID \
 --from-file="private_key=$TEMPORAL_FOLDER/key" | \
   jq '.metadata.labels |= {{ include "newrelic.common.labels" . | fromYaml | toJson }}' | \
   kubectl apply -n "{{ .Release.Namespace }}" -f -
@@ -136,7 +254,7 @@ helm.sh/hook-weight: "-1010"
   namespace: {{ .Release.Namespace }}
 rules:
   - apiGroups: [ "" ]
-resources: ["secrets"]
+resources: [ "secrets" ]
 verbs:
   - create
   - patch
@@ -159,9 +277,9 @@ roleRef:
   kind: ClusterRole
   name: {{ include "newrelic.common.naming.truncateToDNSWithSuffix" (dict "name" (include "newrelic.common.naming.fullname" .) "suffix" "auth") }}
 subjects:
-- kind: ServiceAccount
-  name: {{ include "newrelic.common.naming.truncateToDNSWithSuffix" (dict "name" (include "newrelic.common.serviceAccount.name" .) "suffix" "auth" ) }}
-  namespace: {{ .Release.Namespace }}
+  - kind: ServiceAccount
+name: {{ include "newrelic.common.naming.truncateToDNSWithSuffix" (dict "name" (include "newrelic.common.serviceAccount.name" .) "suffix" "auth" ) }}
+namespace: {{ .Release.Namespace }}
 {{- end }}
 
 {{- if include "newrelic.common.serviceAccount.create" . }}
